export const sections = [
  {
    slug: 'home',
    title: 'Home',
    label: '总览入口',
    description: '项目首页，负责承接全局概况和快捷跳转。',
    accent: '#0f766e',
    stats: ['今日活跃 12.8k', '待处理事项 18', '转化率 31.2%'],
    related: ['dashboard', 'reports', 'support'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看平台总览、入口导航和关键指标。' },
      { slug: 'updates', title: 'Updates', summary: '追踪最近的版本更新与公告。' },
      { slug: 'shortcuts', title: 'Shortcuts', summary: '通过快捷入口跳转到其它业务模块。' },
    ],
  },
  {
    slug: 'dashboard',
    title: 'Dashboard',
    label: '运营驾驶舱',
    description: '集中展示运营看板、趋势与异常信息。',
    accent: '#2563eb',
    stats: ['实时订单 1,284', '异常告警 4', '履约完成率 97.5%'],
    related: ['analytics', 'orders', 'reports'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '浏览驾驶舱总览、实时指标和热点模块。' },
      { slug: 'alerts', title: 'Alerts', summary: '查看当前告警和需要跟进的事件。' },
      { slug: 'timeline', title: 'Timeline', summary: '按时间轴追踪业务变化和波动。' },
    ],
  },
  {
    slug: 'analytics',
    title: 'Analytics',
    label: '数据分析',
    description: '分析用户、渠道和活动的核心趋势。',
    accent: '#7c3aed',
    stats: ['周留存 58%', '自然流量 +14%', '渠道 ROI 2.7'],
    related: ['marketing', 'customers', 'reports'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看分析首页与关键漏斗。' },
      { slug: 'funnels', title: 'Funnels', summary: '按转化漏斗拆解用户行为。' },
      { slug: 'segments', title: 'Segments', summary: '对用户分群进行深入分析。' },
    ],
  },
  {
    slug: 'products',
    title: 'Products',
    label: '商品中心',
    description: '管理商品目录、定价和上新节奏。',
    accent: '#c2410c',
    stats: ['在售商品 386', '低库存 27', '新品计划 9'],
    related: ['orders', 'inventory', 'marketing'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看商品库、类目结构和主推商品。' },
      { slug: 'catalog', title: 'Catalog', summary: '维护类目与商品清单。' },
      { slug: 'pricing', title: 'Pricing', summary: '管理价格带、折扣和策略。' },
    ],
  },
  {
    slug: 'orders',
    title: 'Orders',
    label: '订单中心',
    description: '处理交易、履约进度和售后状态。',
    accent: '#be185d',
    stats: ['待发货 73', '退款中 11', '客单价 286'],
    related: ['products', 'inventory', 'customers'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '汇总订单状态和履约概况。' },
      { slug: 'queue', title: 'Queue', summary: '处理待确认、待发货和异常订单。' },
      { slug: 'returns', title: 'Returns', summary: '跟进退款、退货与售后单。' },
    ],
  },
  {
    slug: 'customers',
    title: 'Customers',
    label: '客户运营',
    description: '观察用户分层、反馈与生命周期。',
    accent: '#0891b2',
    stats: ['高价值用户 624', '新增注册 318', 'NPS 48'],
    related: ['analytics', 'marketing', 'support'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看客户总览和人群结构。' },
      { slug: 'profiles', title: 'Profiles', summary: '查看客户画像、标签与偏好。' },
      { slug: 'journeys', title: 'Journeys', summary: '分析客户生命周期路径。' },
    ],
  },
  {
    slug: 'marketing',
    title: 'Marketing',
    label: '营销活动',
    description: '规划活动节奏、渠道投放与内容传播。',
    accent: '#ea580c',
    stats: ['活动进行中 6', '内容素材 42', '投放预算 120k'],
    related: ['analytics', 'customers', 'docs'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看营销日历和当前活动。' },
      { slug: 'campaigns', title: 'Campaigns', summary: '管理活动方案与投放节奏。' },
      { slug: 'channels', title: 'Channels', summary: '拆解渠道表现与触点效果。' },
    ],
  },
  {
    slug: 'reports',
    title: 'Reports',
    label: '报表中心',
    description: '整理经营周报、月报和专题分析。',
    accent: '#4f46e5',
    stats: ['待发布报表 3', '本周导出 127', '同比增长 11.4%'],
    related: ['dashboard', 'analytics', 'finance'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看所有报表入口和最近更新。' },
      { slug: 'weekly', title: 'Weekly', summary: '浏览周报摘要与主要结论。' },
      { slug: 'exports', title: 'Exports', summary: '管理导出任务和共享链接。' },
    ],
  },
  {
    slug: 'settings',
    title: 'Settings',
    label: '系统设置',
    description: '统一配置团队、权限与系统偏好。',
    accent: '#334155',
    stats: ['团队成员 28', '角色模板 6', '待审权限 2'],
    related: ['profile', 'support', 'home'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '进入系统设置首页和基础配置。' },
      { slug: 'permissions', title: 'Permissions', summary: '管理角色权限和访问策略。' },
      { slug: 'preferences', title: 'Preferences', summary: '配置主题、通知和工作偏好。' },
    ],
  },
  {
    slug: 'support',
    title: 'Support',
    label: '支持中心',
    description: '汇总帮助文档、工单和响应进度。',
    accent: '#0f766e',
    stats: ['处理中工单 19', '平均响应 13m', '解决率 94%'],
    related: ['customers', 'settings', 'docs'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看支持中心总览与当前服务状态。' },
      { slug: 'tickets', title: 'Tickets', summary: '管理工单池与处理优先级。' },
      { slug: 'knowledge', title: 'Knowledge', summary: '维护知识库与常见问题。' },
    ],
  },
  {
    slug: 'profile',
    title: 'Profile',
    label: '个人空间',
    description: '管理个人信息、任务和通知。',
    accent: '#9333ea',
    stats: ['待办 7', '未读提醒 15', '最近登录 09:30'],
    related: ['settings', 'support', 'home'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看个人工作台和常用入口。' },
      { slug: 'tasks', title: 'Tasks', summary: '跟进待办、审批和协作提醒。' },
      { slug: 'notifications', title: 'Notifications', summary: '统一处理系统通知和消息。' },
    ],
  },
  {
    slug: 'docs',
    title: 'Docs',
    label: '文档中心',
    description: '存放前端规范、接口文档和组件说明。',
    accent: '#0369a1',
    stats: ['文档总数 214', '待更新 8', '本周访问 2.3k'],
    related: ['support', 'settings', 'home'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看文档中心首页和文档分类。' },
      { slug: 'guides', title: 'Guides', summary: '阅读使用指南与最佳实践。' },
      { slug: 'components', title: 'Components', summary: '浏览组件清单、规范和示例。' },
    ],
  },
  {
    slug: 'inventory',
    title: 'Inventory',
    label: '库存仓储',
    description: '跟踪库存分布、预警与补货计划。',
    accent: '#15803d',
    stats: ['仓库 5', '缺货 SKU 14', '补货计划 12'],
    related: ['products', 'orders', 'reports'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '浏览库存总览与仓储状态。' },
      { slug: 'stock', title: 'Stock', summary: '查看库存分布、批次和安全库存。' },
      { slug: 'replenishment', title: 'Replenishment', summary: '制定补货与调拨计划。' },
    ],
  },
  {
    slug: 'finance',
    title: 'Finance',
    label: '财务经营',
    description: '关注收支、利润和结算状态。',
    accent: '#b45309',
    stats: ['本月收入 3.2M', '利润率 24%', '待结算 96k'],
    related: ['reports', 'orders', 'dashboard'],
    children: [
      { slug: 'overview', title: 'Overview', summary: '查看财务总览和经营健康度。' },
      { slug: 'billing', title: 'Billing', summary: '处理账单、发票和结算。' },
      { slug: 'profit', title: 'Profit', summary: '分析利润结构与成本波动。' },
    ],
  },
]

export const sectionMap = Object.fromEntries(sections.map((section) => [section.slug, section]))

export function buildPath(sectionSlug, childSlug) {
  return `/${sectionSlug}/${childSlug}`
}
